--
apiVersion: v1
kind: Namespace
metadata:
  name: homebridge
  labels:
    name: home
---
kind: StatefulSet
apiVersion: apps/v1
metadata:
  name: homebridge
  namespace: homebridge
spec:
  serviceName: "homebridge"
  replicas: 1
  selector:
    matchLabels:
      name: homebridge
  template:
    metadata:
      name: homebridge
      labels:
        name: homebridge
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: homebridge
          securityContext:
            privileged: true
            #image: 'docker.io/oznu/homebridge:latest'
          image: 'docker.io/oznu/homebridge:no-avahi'
          volumeMounts:
            - name: homebridge
              mountPath: /homebridge
              subPath: homebridge
          env:
            - name: PGID
              value: "9092"
            - name: PUID
              value: "1000"
            - name: HOMEBRIDGE_CONFIG_UI
              value: "1"
            - name: HOMEBRIDGE_CONFIG_UI_PORT
              value: "8581"
            - name: TZ
              value: "Europe/Paris"
  volumeClaimTemplates:
  - metadata:
      name: homebridge
    spec:
      storageClassName: "nfs-storageclass"
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi

---
apiVersion: v1
kind: Service
metadata:
  name: host-network-homebridge
  namespace: homebridge
  labels:
      app: homebridge
spec:
  ports:
  - port: 8581
    name: homebridge-ui
  clusterIP: None
  selector:
    app: homebridge
